apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service
  namespace: gojobs
  labels:
    k8s-app: account-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: account-service
        name: account-service
    spec:
      containers:
      - name: account-service
        image: registry.ckmro.com:1180/gojobs/accountservice
        ports:
        - containerPort: 6767
          protocol: TCP
      - name: mongo
        image: registry.ckmro.com:1180/library/mongo
        ports:
        - containerPort: 32017
          protocol: TCP
      imagePullSecrets:
      - name: harborsecret